%YAML 1.0
---
sensors:
  imu:
    topic: /sensors/bno08x/raw
    sample_rate: 400
    bus: 1

  distance:
    topic: /sensors/vl53l0x/dist
    sample_rate: 400
    bus: 1

  color:
    topic: /sensors/tcs34725/color
    sample_rate: 100
    pins:
      s2: 19
      s3: 26
      signal: 13

  camera:
    topic: /sensors/imx/compressed
    sample_rate: 30 # is also framerate
    input_stream: 0
    resolution:
      width: 640
      height: 480

  battery:
    sample_rate: 0.5
    sensors:
      - topic: /sensors/ina219_0/state # sensors battery
        max_cell_voltage: 4.2
        min_cell_voltage: 3.8
        cells: 2
        capacity: 1800 # mAh
        bus: 1

      - topic: /sensors/ina219_1/state # motors battery
        max_cell_voltage: 4.2
        min_cell_voltage: 3.8
        cells: 3
        capacity: 2300 # mAh
        bus: 0

actuators:
  motors:
    topic: /cmd_vel
    sample_rate: 100
    esc_pin: 14
    servo_pin: 15

  flare: # led tape
    topic: /flare
    pin: 18

  led: # onboard signal leds
    - topic: /led_0
      pin: 17
    - topic: /led_1
      pin: 27

visual_odometry:
  node: visual_odometry
  topic: /visual_odometry/pose
  path_topic: /visual_odometry/path
  sample_rate: 10

estimator:
  node: estimator
  topic: /estimator/pose
  sample_rate: 100

mapper:
  node: mapper
  topic: /mapper/map
  sample_rate: 100
  seg_pts_num: 100

visual_pid:
  node: visual_pid
  topic: /visual_pid/cmd_vel
  show_topic: /visual_pid/debug_image
  sample_rate: 20
  correction: 5 # degrees
  confidence_threshold: 0.6
  error_threshold: 10 # pixels