%YAML 1.0
sensors:
  imu:
    topic: /sensors/bno08x/raw
    sample_rate: 300
    bus: 1

  distance:
    topic: /sensors/vl53l0x/dist
    sample_rate: 300
    bus: 1

  color:
    topic: /sensors/tcs34725/color
    sample_rate: 100
    pins:
      s2: 19
      s3: 26
      signal: 13

  camera:
    topic: /sensors/imx/image_raw
    sample_rate: 30 # is also framerate
    input_stream: csi://0
    resolution:
      width: 640
      height: 480

  battery:
    sample_rate: 1
    topic: 
      # sensors battery
      - /sensors/ina219_0/state 
      # motors battery
      - /sensors/ina219_1/state 
    type: 
      - LIHV
      - LIPO
    cells: 
      - 3
      - 2
    capacity: 
      - 2300 # mAh
      - 1800 # mAh
    bus:
      - 1
      - 0

actuators:
  motors:
    topic: /cmd_vel
    brake_topic: /brake
    use_brake: 1
    esc_channel: 0
    servo_channel: 1
    max_speed: 30
    angle_step: 5 # degrees
    speed_step: 0.05 

  flare: # led tape
    topic: /flare
    pin: 18
    # pin: 12

  led: # onboard signal leds
    topics: 
      - /led_1
      - /led_2
    pins:
      red: # linux gpio notation
        - 51
        - 50
      green:
        - 77
        - 14 
      blue:
        - 78
        - 194

cone_detector:
  topic: /cone_detector/detections
  sample_rate: 10
  confidence_threshold: 0.6
  error_threshold: 10 # pixels
  model_path: /home/user/ws/Data/models/Yolov4_cones_epoch20.pth
  debug_img: 1
  debug_topic: /cone_detector/debug_image

mapper:
  node: mapper
  topic: /mapper/map
  sample_rate: 100
  seg_pts_num: 100

visual_pid:
  node: visual_pid
  topic: /visual_pid/cmd_vel
  show_topic: /visual_pid/debug_image
  sample_rate: 20
  correction: 5 # degrees
  confidence_threshold: 0.6
  error_threshold: 10 # pixels

steering:
  odometry_topic: /ov_msckf/loop_pose
  map_topic: /steering/map
  map_file: /home/user/ws/Data/maps/track.txt
  mark_color_lower:
    - 3200
    - 3200
    - 2000
  mark_color_upper:
    - 4200
    - 4200
    - 3500

slam:
  mark_color_lower:
    - 3200
    - 3200
    - 2000
  mark_color_upper:
    - 4200
    - 4200
    - 3500
  pid:
    kp: 0.15
    ki: 0.0
    kd: 0.001
  ignore_first_n: 50
  linear_speed: 0.16
  ignore_first_mark: 5.0
  ang_accel_min: 0.001

pose_logger:
  topic: /ov_msckf/loop_pose
  output_file: /home/user/ws/Data/maps/track.txt
  skip_poses: 50

visualization_node:
  topics:
    # - /steering/map
    # - /fake_pose
    # - /ov_msckf/posegt
    - /interII/loop_pose