%YAML 1.0
---
sensors:
  imu:
    node: bno08x
    topic: sensors/bno08x/raw
    sample_rate: 400

  distance:
    node: vl53l0x
    topic: sensors/vl53l0x/dist
    sample_rate: 400

  color:
    node: tcs34725
    topic: sensors/tcs34725/color
    sample_rate: 100
    pins:
      s2: 23
      s3: 24
      signal: 25

  camera:
    node: imx
    topic: sensors/imx/compressed
    sample_rate: 30 # is also framerate
    input_stream: 0
    resolution:
      width: 640
      height: 480

  battery:
    node: ina219
    topic: sensors/ina219/voltage
    sample_rate: 0.5
    max_cell_voltage: 4.2
    min_cell_voltage: 3.8
    cells: 2
    capacity: 1800 # mAh

motors:
  node: drive_control
  topic: cmd_vel
  sample_rate: 100
  esc_pin: 14
  servo_pin: 15

led:
  node: signal_led
  topic: mark
  mark_color_upper: [100, 100, 100] # 69 69 62
  mark_color_lower: [10, 30, 10]
  deactivation_delay: 0.5

imu_tracker:
  node: imu_tracker
  topic: imu_tracker/pose
  sample_rate: 400

visual_odometry:
  node: visual_odometry
  topic: visual_odometry/pose
  path_topic: visual_odometry/path
  sample_rate: 10

estimator:
  node: estimator
  topic: estimator/pose
  sample_rate: 100

mapper:
  node: mapper
  topic: mapper/map
  sample_rate: 100
  seg_pts_num: 100

visual_pid:
  node: visual_pid
  topic: visual_pid/cmd_vel
  show_topic: visual_pid/debug_image
  sample_rate: 20
  correction: 5 # degrees
  confidence_threshold: 0.6
  error_threshold: 10 # pixels