%YAML 1.0
sensors:
  imu:
    topic: /sensors/bno08x/raw
    sample_rate: 300
    bus: 1

  distance:
    topic: /sensors/vl53l0x/dist
    sample_rate: 300
    bus: 1

  color:
    topic: /sensors/tcs34725/color
    sample_rate: 100
    pins:
      s2: 19
      s3: 26
      signal: 13

  camera:
    topic: /sensors/imx/image_raw
    sample_rate: 30 # is also framerate
    input_stream: csi://0
    resolution:
      width: 640
      height: 480

  battery:
    sample_rate: 0.5
    topic: 
      - /sensors/ina219_0/state # sensors battery
      - /sensors/ina219_1/state # motors battery
    type: 
      - LIPO
      - LIHV
    cells: 
      - 2
      - 3
    capacity: 
      - 1800 # mAh
      - 2300 # mAh
    bus:
      - 1
      - 0

actuators:
  motors:
    topic: /cmd_vel
    sample_rate: 100
    esc_pin: 14
    servo_pin: 15

  flare: # led tape
    topic: /flare
    pin: 18

  led: # onboard signal leds
    topics: 
      - /led_1
      - /led_2
    pins:
      red: # linux gpio notation
        - 51
        - 50
      green:
        - 77
        - 14 
      blue:
        - 78
        - 194

cone_detector:
  topic: /cone_detector/detections
  sample_rate: 10
  confidence_threshold: 0.6
  error_threshold: 10 # pixels
  model_path: /home/user/ws/Data/models/yolov5-cone-best.pt
  debug_img: 1
  debug_topic: /cone_detector/debug_image

mapper:
  node: mapper
  topic: /mapper/map
  sample_rate: 100
  seg_pts_num: 100

visual_pid:
  node: visual_pid
  topic: /visual_pid/cmd_vel
  show_topic: /visual_pid/debug_image
  sample_rate: 20
  correction: 5 # degrees
  confidence_threshold: 0.6
  error_threshold: 10 # pixels

visualization_node:
  topics:
    # - /fake_pose
    # - /ov_msckf/posegt
    - /ov_msckf/loop_pose